import { Geist, Geist_Mono, Inter, Poppins } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Navber from "@/shared/Navber";
import Footer from "@/shared/Footer";

export const poppins = Poppins({
    variable: "poppins",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700", "800", "900"]
});

export const inter = Inter({
    variable: "inter",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700", "800", "900"]
});

const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html
            lang="en"
            data-theme="light"
            className={`h-full antialiased`}
        >
            <body className={`min-h-full flex flex-col ${inter.className} ${poppins.className}`}>
                <Navber></Navber>
                {children}
                <Footer></Footer>
                <ToastContainer />
            </body>
        </html>
    );
}
